appName: listings
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/listing-service
appVersion: "1.0.7"
appReplicas: 1
containerPort: 5001
containerEnvVars: 
- name: PORT
  value: "5001"
- name: NODE_ENV
  value: "production"
- name: PROPERTY_SERVICE_URL
  value: "http://property:5004"
- name: PRICE_SERVICE_URL
  value: "http://price:5006"

servicePort: 5001
