appName: platform
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/platform-service
appVersion: '{{ requiredEnv "IMAGE_TAG" }}'
appReplicas: 2
containerPort: 5010
containerEnvVars: 
- name: PORT
  value: "5010"
- name: NODE_ENV
  value: "production"
- name: LISTINGS_SERVICE_URL
  value: "http://listings:5001"
- name: USERS_SERVICE_URL
  value: "http://users:5002"
- name: TENANTS_SERVICE_URL
  value: "http://tenant:5003"
- name: PROPERTY_SERVICE_URL
  value: "http://property:5004"
- name: INVENTORY_SERVICE_URL
  value: "http://inventory:5005"
- name: PRICE_SERVICE_URL
  value: "http://price:5006"
- name: SEARCH_SERVICE_URL
  value: "http://search:5007"
- name: RELEASE_NAME
  value: "fizzy postcard"
- name: NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: GPU_RELEASE
  value: "COTOPAXI"
- name: LISTINGS_IMAGE_TAG
  value: "1.0.7"
- name: USERS_IMAGE_TAG
  value: "1.0.9"
- name: TENANTS_IMAGE_TAG
  value: "1.0.9"
- name: PROPERTY_IMAGE_TAG
  value: "1.0.9"
- name: INVENTORY_IMAGE_TAG
  value: "1.0.9"
- name: PRICE_IMAGE_TAG
  value: "1.0.7"
- name: PLATFORM_IMAGE_TAG
  value: "1.0.8"
- name: SEARCH_IMAGE_TAG
  value: "1.0.4"

serviceType: LoadBalancer
servicePort: 5010
