appName: price
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/price-service
appVersion: "1.0.5"
appReplicas: 1
containerPort: 5006
containerEnvVars: 
- name: PORT
  value: "5006"
- name: NODE_ENV
  value: "production"

servicePort: 5006
