appName: tenant
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/tenant-service
appVersion: "1.0"
appReplicas: 1
containerPort: 5003
containerEnvVars: 
- name: PORT
  value: "5003"

servicePort: 5003