appName: users
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/user-services
appVersion: "1.0"
appReplicas: 1
containerPort: 5002
containerEnvVars: 
- name: PORT
  value: "5002"

servicePort: 5002