appName: users
appImage: 762760349103.dkr.ecr.eu-north-1.amazonaws.com/microservices/user-services
appVersion: '{{ requiredEnv "IMAGE_TAG" }}'
appReplicas: 2
containerPort: 5002
containerEnvVars: 
- name: PORT
  value: "5002"
- name: NODE_ENV
  value: "production"

servicePort: 5002
