apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imageSecrets }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: {{ .Values.containerPort}}
        env:
        {{- range .Values.containerEnvVars}}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end}}
        envFrom:
        - secretRef:
            name: {{ .Values.secretName }}
        resources:
          requests: 
            cpu: {{ .Values.cpuRequest }}
            memory: {{ .Values.memoryRequest }}
          limits:
            cpu: {{ .Values.cpuLimits }}
            memory: {{ .Values.memoryLimits}}
       