environments:
  development:
    values:
      - namespace: development
  staging:
    values:
      - namespace: staging

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: false
  timeout: 1200

releases:
  - name: postgres
    namespace: '{{ .Values.namespace | default "development" }}'
    chart: bitnami/postgresql
    values:
      - helm-postgre.yaml

  - name: inventoryservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/inventory-service-values.yaml

  - name: listingservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/listing-service-values.yaml

  - name: platformservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/platform-service-values.yaml

  - name: priceservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/price-service-values.yaml

  - name: searchservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values:
      - Values/search-service-values.yaml

  - name: propertyservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/property-service-values.yaml

  - name: tenantservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/tenant-service-values.yaml

  - name: userservice
    namespace: '{{ .Values.namespace | default "development" }}'
    needs:
      - postgres
    chart: microservice
    values: 
      - Values/users-service-values.yaml

  
